### ISSUE TITLE
Email validation and alert. 

### ISSUE THREAD

**Issue by Bruhmoss** [Jon-Peppinck/social-posts#19]
Is there a way to add email validation at client side that the email already exists? Running the app just gives server error on console but no alert at client side.

**Comment by Jon-Peppinck** [comment]
In the response return the error response to the client. It is up to the client how to consume this. For example, in my LinkedIn clone project I handle this with a toast popup. You could also choose to show this error in a mat-error. I will leave this up to the viewer to decide on how they want to handle this and whether or not they want to implement it.
